### ISSUE TITLE
make building base as kubebb components

### ISSUE THREAD

**Issue by bjwswang** [kubebb/components#6]
Steps to deploy building base

- [x] deploy cluster component https://github.com/kubebb/building-base/tree/main/u4a-component/charts/cluster-component
- [x] #33

**Comment by bjwswang** [comment]
## Cluster Components

- [ ] Ingress Nginx
- [ ] Cert Manager
- [ ] openebs
- [ ] metallb

## Addon Components

- kube-oidc-proxy
- tenant-management: capsule

## U4a Components

**Comment by 0xff-dev** [comment]
close ?

**Comment by bjwswang** [comment]
verified?

**Comment by 0xff-dev** [comment]
wait  https://github.com/kubebb/core/issues/137 https://github.com/kubebb/core/issues/105
