### ISSUE TITLE
Use kubebb menus in u4a-component

### ISSUE THREAD

**Issue by bjwswang** [kubebb/components#62]
- [ ] Change menus to kubebb crd
- [ ] Update bff server image to `kubebb/bff-server-ce:`

**Comment by 0xff-dev** [comment]
- hub.tenxcloud.com/u4a-component/bff-server:v0.1.0-20230423
- hub.tenxcloud.com/u4a-component/oidc-server:v0.1.0-20230209
- hub.tenxcloud.com/u4a-component/iam-provider:v0.1.0-20230513
- ldap          u4a_system/openldap:1.5.0 , u4a_system/phpldapadmin:stable
- hub.tenxcloud.com/u4a-component/resource-viewer:v0.1.0-20221024
-

**Comment by 0xff-dev** [comment]
new image

- kubebb/bff-server:v0.1.0
- kubebb/oidc-server:v0.1.0
- kubebb/iam-provider:v0.1.0
- kubebb/resource-viewer:v0.1.0
