### ISSUE TITLE
run bffserver with community version

### ISSUE THREAD

**Issue by bjwswang** [kubebb/components#78]

**Comment by 0xff-dev** [comment]
- hub.tenxcloud.com/u4a-component/bff-server:v0.1.0-20230423
- hub.tenxcloud.com/u4a-component/oidc-server:v0.1.0-20230209
- hub.tenxcloud.com/u4a-component/iam-provider:v0.1.0-20230513
- ldap          u4a_system/openldap:1.5.0 , u4a_system/phpldapadmin:stable
- hub.tenxcloud.com/u4a-component/resource-viewer:v0.1.0-20221024

**Comment by bjwswang** [comment]
duplicated with #62
